Repository Team-ticku/ticku_BE, pull requests merged in 2025-03, with the labels that each got.

#6 chore: 라우팅 재설정
  models/Post.js
  models/User.js
  routes/posts.js
  routes/users.js
  ticku-server.js
Labels: 🐆 장우, chore

#4 [FEAT] 회원가입, 로그인 기능 추가
  .gitignore
  models/User.js
  package-lock.json
  package.json
  routes/auth.js
  ticku-server.js
Labels: ✨ feat, 🐶 민정

#10 [FEAT]배당락일 캘린더 프론트엔드 연결
  models/Calen.js
  routes/calens.js
  ticku-server.js
Labels: ✨ feat, 🐧 소현

#11 [FEAT] 검색엔진 검색 API 구현
  models/Company.js
  routes/search.js
  ticku-server.js
Labels: ✨ feat, 🐻‍❄️ 은비

#14 [FEAT] 사용자 정보 가져오기, 수정 기능 추가
  models/User.js
  public/img/image-1741746290986.jpg
  routes/user.js
  routes/users.js
  ticku-server.js
Labels: ✨ feat, 🐶 민정, chore

#16 [FEAT] 세부 설명 페이지 기능 구현
  models/Explain.js
  routes/explains.js
  ticku-server.js
Labels: ✨ feat, 🐱 하은

#17 [FEAT] 주가 정보 및 차트 추가
  routes/allchartdata.js
  routes/search.js
  routes/stockdata.js
  ticku-server.js
Labels: ✨ feat, 🐆 장우

#19 [FEAT] 관심기업 콜렉션 추가, 관심 기업 가져오기, 삭제 기능 추가
  models/Favorites.js
  routes/user.js
Labels: ✨ feat, 🐶 민정

#22 [FEAT] 기업 재무 페이지 API 연결
  routes/chart.js
  routes/companyInfo.js
  routes/yearResult.js
  ticku-server.js
Labels: ✨ feat, 🐆 장우

#24 [FEAT] 스크랩한 뉴스 컬렉션 추가, 스크랩한 뉴스 가져오기, 삭제 기능 추가
  models/ScrapNews.js
  routes/user.js
Labels: ✨ feat, 🐶 민정

#26 [FEAT] 포트폴리오 차트 백엔드 연결
  models/Portfolio.js
  routes/portfolios.js
  ticku-server.js
Labels: ✨ feat, 🐧 소현

#30 [FEAT] 메인페이지 실시간 지수 API 구현
  models/IndexData.js
  routes/indexData.js
  ticku-server.js
Labels: ✨ feat, 🐻‍❄️ 은비

#33 [FEAT] 연간, 분기 실적 데이터 API
  routes/quarterlySales.js
  routes/salesyear.js
  ticku-server.js
Labels: ✨ feat, 🐆 장우

#34 [FEAT] 메인페이지 실시간 검색어 순위 API 구현
  package-lock.json
  package.json
  routes/searchRanking.js
  ticku-server.js
Labels: ✨ feat, 🐻‍❄️ 은비

#36 [FEAT] 내 포트폴리오 가져오기, 핀 수정 추가
  routes/user.js
Labels: ✨ feat, 🐶 민정

#39 [FEAT] 뉴스 페이지 API 제작
  package-lock.json
  package.json
  routes/news.js
  ticku-server.js
Labels: ✨ feat, 🐆 장우

#40 [FEAT]사용자 대표 포트폴리오 가져오기
  routes/portfolios.js
Labels: ✨ feat, 🐶 민정

#43 [FEAT] 뉴스 스크랩 저장 및 삭제
  models/ScrapNews.js
  routes/user.js
Labels: ✨ feat, 🐆 장우

#44 [FEAT] 관심 기업 DB에서 불러오기, 저장, 삭제
  routes/star.js
  ticku-server.js
Labels: ✨ feat, 🐶 민정

#47 [FIX] 전송할 뉴스 갯수 10개로 수정
  routes/news.js
Labels: 🐆 장우, 🔧 fix

#48 [FEAT 스크랩한 뉴스 불러오기, 저장, 삭제
  models/ScrapNews.js
  routes/bookmark.js
  routes/user.js
  ticku-server.js
Labels: ✨ feat, ♻️ refactor, 🐶 민정

#50 [FEAT] [FIX] 커뮤니티 API 연결 수정
  package-lock.json
  package.json
  public/img/image-1741746290986.jpg
  routes/community.js
  routes/posts.js
  routes/user.js
  ticku-server.js
  utils/upload.js
Labels: ✨ feat, 🐻‍❄️ 은비, 🔧 fix

#52 [FIX]현재가와 변화량 수정
  routes/stockdata.js
Labels: 🐆 장우, 🔧 fix

#53 [FEAT] 커뮤니티 게시글 수정 API 추가
  routes/community.js
Labels: ✨ feat, 🐻‍❄️ 은비
